

export const lyricsObject = [
    {
        title: "N.A.T.O.",
        englishTitle: "N.A.T.O.",
        english: [
            "North Atlantic contract intoxication",
            "North Atlantic contract capitulation",
            "North Atlantic contract colonization",
            "North Atlantic contract emasculation",
            "North Atlantic contract obliteration",
            "North Atlantic contract sewerage",

        ],
        german: [
            "Nordatlantische Vertrags Intoxikation",
            "Nordatlantische Vertrag Kapitulation",
            "Nordatlantische Vertrag Kolonisation",
            "Nordatlantische Vertrags Emaskulation",
            "Nordatlantische Vertrags Obliteration",
            "Nordatlantische Vertrag Kanalisation",
    ],
        audioUrl: "/album/N.A.T.O..mp3"
    },
    {
        title: "Republik der Twerps",
        englishTitle: "Republic of Twerps",
        english: [
            "Breakfast",
            "Lunch",
            "Dinner",
            "Bedtime",
            "Nightmares",
            "Squeeze the corn",
            "Fry the eagle’s egg",
            "Bake the last bear",
            "Breakfast in the Republic of twerps",
            "Mayonnaise on a Drone",
            "Ketchup on submarines",
            "Turkey skin satellite",
            "Lunchtime in the republic of twerps",
            "My child has a potato head",
            "and a heartbeat of gravy",
            "Plentiful napkins forever",
            "Suppertime in the republic of twerps",
            "Break",
            "Apple pie made from mucus?" ,
            "You deserve a break today",
            "But you won’t get one",
            "Dinner in the republic of Twerps",
        ],
        german: [
            "Frühstück",
            "Mittagessen",
            "Abendessen",
            "Schlafenszeit",
            "Alpträume",
            
            "Den Mais auspressen",
            "Braten sie die Adlereier",
            "Backe den letzten Bären",
            "Frühstück in der Republik der Twerps",
            
            "Mayonnaise auf Drohnen",
            "Ketchup auf U-Booten",
            "Truthahn Haut Satelliten",
            "Mittagspause in der Republik der Twerps",
            
            "Mein Kind hat einen Kartoffelkopf",
            "Und einen Herzschlag aus Sosse",
            "Reichlich Servietten für immer",
            "Abendbrot in der Republik der Twerps",
            "PAUSE",
            "Apfelkuchen aus rotzigem Schnotter",
            "Du verdienst eine Pause heute",
            "aber du kriegst keine",
            "Abendbrot in der Republik der Twerps"

        ],
        audioUrl: "/album/Republik-der-Twerps.mp3"
        
    },
    {
        title: "Doms",
        englishTitle: "Doms",
        english: [
            "Giant Dom.....",
            "NO!",
            "It is possible",
            "The Defenestration of the Rulers",
            "The fall is soft, cushioned by the dung heaps",
            "Run ruler, run! Escape from the dung wagons",
            "Little Dom.....",
            "Yes!",
            "That's better my friend!",
            "We're all little doms, aren't we?"
        ],
        german: [
            "Giant Dom...",
            "Nein!",
            "Es ist möglich",
            "Der Fenstersturz der Herrscher",
            "Der Fall ist weich, abgefedert von den Misthaufen",
            "Lauf Herrscher, lauf Fliehe von den Mistwagen",
            "Little Dom…..",
            "Ja!",
            "Das ist besser, mein Freund!",
            "Wir sind alle little Doms, nicht wahr?"
        ],
        audioUrl: "/album/Doms.mp3"
    },
    {
        title: "Hand",
        englishTitle: "Hand",
        english: [
            "Hand",
            "Atom hand", 
            "Amoeba hand",
            "Crab hand (dungeon crab pinches)",
            "Fish hand",
            "Toad hand",
            "Snake hand",
            "Rodent hand",
            "Dog hand",
            "Monkey hand (Subliminal hand)",
            "Man hand (Liminal hand)",
            "Devil hand (Superliminal hand)",
            "Angel hand",
            "Machine hand",
            "Atom hand", 
        ],
        german: [
            "Hand",
            "Atom hand",
            "Amöben hand",
            "Krabben hand (Kerker Krabbe kneift)",
            "Fish hand",
            "Kröten hand",
            "Schlangen hand",
            "Nagetier Hand",
            "Hunde Hand",
            "Affenhand",
            'Unterschwellige Hand',
            "Mann Hand",
            "Begrenzte Hand",
            "Teufels Hand",
            "Überschwellige Hand",
            "Engels Hand",
            "Maschinen Hand",
            "Atom Hand"
            
        ],
        audioUrl: "/album/Hand.mp3"
    },
    {
        title: "Scheisse Klein",
        englishTitle: "Little Shit",
        english: [
            "Mittenstein",
            "Poets pants",
            "Squirt the shits in my lederhosen",
            "A shit a mine",
            "No shit no mine",
            "Arborhudel smallhudel hudelsmall",
            "No shit small",
            "No little shit",
            "A little shit small",
            "Mittenstein my lederhosen",
            "Squirt shit in my lederhosen",
            "Squirt a shit",
            "My little one",
            "With the master",
            "Small bill"
        ],
        german: [
            "Mittenenstein",
            "Dichterhosen",
            "Spritz scheisse in mein Lederhosen",
            "Ein scheisse ein mein",
            "Logahudel nee  kleckenhudel",
            "Mittenstein",
            "Dichterhosen",
            "Spritz scheisse in mein Lederhosen",
            "Nein scheisse nein mein",
            "Laubenhudel Kleinhudel Hudelklein",
            "Nein scheisse klein",
            "Nein scheisse klein",
            "Einen kleinen Scheisse kleinen",
            "Mittenstein mein Lederhosen",
            "Spritz scheisse ein",
            "Mein kleiner ein",
            "Mit dem Meister",
            "Kleinen Schein"
        ],
        audioUrl: "/album/Scheisse-Klein.mp3"
    },
    {
        title: "Bedenke Dies",
        englishTitle: "Consider This",
        english: [
            "A group of children interview an aspiring clubhouse member",
            "A woodpecker taps Shaksperian sonnets in morse code upon the mailbox of an abandoned farmhouse.",
            "A miniature American flag is placed next to the gravestone of a dog.",
            "Ahh, I should consider these things",
            "I will consider these things",
            "YOU will consider these things",
            "An Automatic Teller Machine dispenses an envelope sealed with a blob of wax.",
            "A highschool football game takes place in the crater of a dormant volcano.",
            "A chimpanzee traces the infinity symbol on a dirty delivery truck door.",
            "Ahh, I should consider these things",
            "I will consider these things",
            "YOU will consider these things"

        ],
        german: [
            "Eine Gruppe von Kindern interviewt ein aufstrebendes Klubhaus-Mitglied.",
            "Ein Specht klopft Shakespeare-Sonetts im Morsecode auf den Briefkasten eines verlassenen Bauernhauses.",
            "Eine Miniatur einer amerikanischen Flagge ist neben dem Grab eines Hundes platziert. ",
            "Er war ein guter Hund",
            
            "Ahh, ich sollte diese Dinge berücksichtigen",
            "Ich werde diese Dinge berücksichtigen",
            "SIE sollten diese Dinge berücksichtigen",
            
            "Ein Geldautomat gibt einen mit einem Klecks aus Wachs versiegelten Umschlag aus.",
            "Ein Hochschul-Fußballspiel  findet im Krater eines ruhenden Vulkans statt.",
            "Ein Schimpanse zeichnet das Unendlichkeitssymbol auf eine schmutzige Lieferwagen-Tür.",
            
            "Ahh, ich sollte diese Dinge berücksichtigen",
            "Ich werde diese Dinge berücksichtigen",
            "SIE sollten diese Dinge berücksichtigen",
            
        ],
        audioUrl: "/album/Bedenke-Dies.mp3"
    },
    {
        title: "Sabische Symbole",
        englishTitle: "Sabian Symbols",
        english: [
            "A dove builds her nest out of obsolete phone cables.",
            "A giraffe's head peaks through a posh penthouse window. ",
            "A stolen mannequin is used for target practice.",
            "A bandaged finger presses a doorbell.",
            "A rattle snake with two heads coils its body to spell the name, 'Sandra'."
        ],
        german: [
            "Eine Taube baut ihr Haus ",
            "Aus veralteten Telefonkabeln",
            "Der Kopf einer Giraffe ragt ",
            "Durch ein nobles Penthouse Fenster",
            "Eine gestohlene Schaufensterpuppe ",
            "Wird für Zielübungen verwendet",
            "Ein bandagierter Finger ",
            "Drückt auf eine Türklingel",
            "Eine Klapperschlange mit zwei Köpfen ",
            "Buchstabiert den Namen Sandra",
            "Sabische Symbole"
            

        ],
        audioUrl: "/album/Sabische-Symbole.mp3"
    },
    {
        title: "Apothekenglocken",
        englishTitle: "Pharmacy Bells",
        english: [
            "Your mouth is bone dry",
            "Because the future scared you.",
            "Listen to the sound of the pharmacy bells.",
            "You have to sit around and wait for them to unblock your tube.",
            "Tap your toes to the beat of the pharmacy bells.",
            "You feel like a puke because your nipples are flaking",
            "Like artichokes, hemorrhoids, halitosis, chickenpox",
            "Oatmeal, skin rash, kidney stone chunks",
            "Tap your toes,",
            "Tap your toes to the beat of the pharmacy bells.",
            "Pharmacy bells"

        ],
        german: [
            "Dein Mund ist knochentrocken ",
            "Denn die Zukunft hat dich erschrocken.",
            "Lausche dem Klang der Apotheken Glocken.",
            "Du musst rumhocken und warten, dass sie deine Röhre aufblocken.",
            "Tippe mit den Zehen im Takt der Apotheken Glocken.",
            "Du fühlst dich wie ein Kotzbrocken weil deine Brustwarzen schuppen ",
            "Wie Artischocken, Hämorriden, Mundgeruch, Windpocken",
            "Haferflocken, Hautausschlag, Nierenstein Brocken",
            "Tippe mit den Zehen,",
            "Tippe mit den Zehen im Takt der Apotheken Glocken.",
            "Apotheken Glocken"

        ],
        audioUrl: "/album/Apothekenglocken.mp3"
    },
    {
        title: "Verbunden",
        englishTitle: "Connected",
        english: [
            "The skull of the foot is connected to the skull of the leg.",
            "The leg skull is connected to the pelvic skull.",
            "The pelvic skull is connected to the spinal skull.",
            "The spinal skull is connected to the head skull.",
            "The head skull is connected to the windows system.",
            "The Windows system is connected to the Skull Grid.",
            "The Skull Grid is connected to the Smart Boot.",
            "The Smart Boot is connected to the foot skull."
        ],
        german: [
            "Der Fußschädel ist mit dem Beinschädel verbunden.",
            "Der Beinschädel ist mit dem Beckenschädel verbunden.",
            "Verbunden",
            "Der Becken Schädel ist mit dem Wirbelsäulenschädel verbunden.",
            "Der Wirbelsäulenschädel ist mit dem Kopfschädel verbunden.",
            "Verbunden",
            "Der Kopfschädel ist mit dem Windowssystem verbunden",
            "Das Windowssystem ist mit dem Schädelnetz verbunden",
            "Verbunden",
            "Das Schädelnetz ist mit dem schlauen Stiefel verbunden",
            "Der schlaue Stiefel ist mit dem Fußschädel verbunden",
            "Verbunden"


        ],
        audioUrl: "/album/Verbunden.mp3"
    },
    {
        title: "Roy Zwei",
        englishTitle: "Roy Two",
        german: [
            "Hier, sein Körper ruht konserviert",
            "Seine Trauernden verbeugen sich im Schmerz",
            "Sie wissen nicht das Plastik die Zukunft sein kann",
            "Wo nur die Besten weiterleben",
            
            "Aber was ist einer Kulturs bester Mann",
            "Wenn sein Begräbnis das Ende ist",
            "Mit Plastik kann es eine Hochzeit sein",
            "Wo unsere Besten weiterleben.",        
            
            "Auf dem Altar liegt eine Opfergabe",
            "Als Sahnehäubchen sein Ebenbild",
            "Wir wissen, das neue Herzschläge unmöglich sind",
            "Ohne die Umarmung mit Plastik",
            
            "Aus dem Herzen seines Frischhhaltefoliengrabes" ,
            "Führt ein Lichtstrahl zu ihm herab",
            "Von dort wo sich neue Konstellationen formen",
            "Die Umrisse von Sonnenbrillengläsern auf einem Gesicht",
            
            "Das Mondlicht scheint durch das Portal",
            "Zu seiner Kammer aus dem Abgrund",
            "Heilige Schwüre aus fleisch und Blut",
            "Ich wecke den Candy Sandman mit einem Kuss",
            "Blast die Trompeten des alten Memphis",
            "Der Tod unserer Besten ist nicht das Ende",
            "Beweis dafür ist hier in meinem Liebesnest",
            
            "Roy Orbison lebt!"
            
        ],
        english: [
            "Here his body lies preserved",
            "As his mourners bow in pain",
           " They don’t know plastics can be a future",
            "Where only the best men live again",
            "But what is a culture’s best man",
            "If his funeral is the end?",
            "With plastic it could be a wedding ",
            "Where our best men live again",
            "At the altar sits an offering ",
            "With our likeness atop the cake",
            "We know new heartbeats are impossible  ",
            "Without the embrace that plastics make",
            "From the heart of his cling-film tomb",
            "A shaft angles toward the place",
            "Where new constellations form ",
            "The outline of sunglasses on a face",
            "As the moonlight shines through the portal ",
            "To his chamber from the abyss" ,
            "Sacred vows are made flesh and blood",
            "When I wake the candy sandman with a kiss",
            "Blow the trumpets of ancient Memphis ",
            "The death of our best men is not the end!",
            "The proof is here within my love nest",
            "Roy Orbison lives again!"
        ],
        audioUrl: "/album/Roy-Zwei.mp3"
    },
    {
        title: "Harlequin Defibrillator",
        englishTitle: "Harlequin Defibrillator",
        english: [
            "1, 2, 3, 4",
            "Harlequin Defibrillator",
        ],
        german: [
            "1, 2, 3, 4",
            "Harlequin Defibrillator",
        ],
        audioUrl: "/album/Harlequin-Defibrillator.mp3"
    },
    {
        title: "Die Unbestreitbaren Vorteile von Milch Gegenüber Wein ",
        englishTitle: "The Undeniable Advantages of Milk Over Wine",
        english: [
            "Riesling",
            "Müller Thurgau",
            "Dornfelder",
            "Grauburgunder",
            "Weissburgunder",
            "Chardonnay",
            "Trollinger",
            "Lemberger",
            "Schwarzriesling",
            "Scheurebe",
            "Gewürztraminer",
            "Merlot",
            "Elbling",
            "Cabernet",
            "Sauvignon",
            "Huxelrebe ",
            "Domina",
            "Frühburgunder",
            "Dunkelfelder",
            
            "All is piss!",
            "Wine is piss!",
            "I am the milkman personally",
            "All is piss!",
            "Wine is piss!",
            "Bring me the milk!",
            
            "Raw milk",
            "Whole milk",
            "2% fat milk",
            "Skimmed milk",
            "Breast milk",
            "Hay milk",
            "Heather milk",
            "Long shelf life milk",
            "Organic milk",
            "Pasture milk",
            "Landmilk",
            "Alpine milk",
            "Fresh milk",
            
            "Pasteurized",
            "Homogenized",
            "Ultra high temperature treated",
            
            "Bring me the milk!",
            "Milk",
            "Wine, milk, wine, milk, wine, milk...",
        ],
        german: [
            "Riesling",
            "Müller Thurgau",
            "Dornfelder",
            "Grauburgunder",
            "Weissburgunder",
            "Chardonnay",
            "Trollinger",
            "Lemberger",
            "Schwarzriesling",
            "Scheurebe",
            "Gewürztraminer",
            "Merlot",
            "Elbling",
            "Cabernet",
            "Sauvignon",
            "Huxelrebe",
            "Domina",
            "Frühburgunder",
            "Dunkelfelder",
            "Alles Pisse",
            "Wein ist Pisse",
            "Ich bin der Milchmann persönlich",
            "Alles Pisse",
            "Wein ist Pisse",
            "Bring mir die Milch",

            "Rohmilch",
            "Vollmilch",
            "Halbfett",
            "Magermilch",
            "Muttermilch",
            "Heumilch",
            "Heidemilch",
            "H-Milch",
            "Biomilch",
            "Weidemilch",
            "Landmilch",
            "Alpenmilch",
            "Frische Milch",
            "Pasteurisiert",
            "Homogenisiert",
            "Ultrahocherhitzt",
            "Bring mir die Milch",
            "Milch",
            "Wein, Milch, Wein , Milch, Wein, Milch..."
        ],
        audioUrl: "/album/Die-Unbestreitbaren-Vorteile-von-Milch-Gegenüber-Wein.mp3"
    },
    {
        title: "Nordstream Pipeline",
        englishTitle: "Nordstream Pipeline",
        english: [
            "What happened to our gas?",
            "Did a swordfish poke the wrong tube?",
            "Bubbles are flying to Valhalla",
            "No",
            "What if we trained some shrimp?",
            "Could they plug the hole with kelp?",
            "Sacrifice of the sea monkey mob",
            "Yes",
            "The shrimp they would be way too stupid",
            "to deal with such treasures",
            "Do you know that these bubbles?",
            "Are like pearls for us?",
            "No",
            "If only we had better helpers?",
            "Maybe the global octopus?",
            "We must save all bubbles",
            "Yes",
            "All our prayers are answered",
            "An octopus tentacle is at the crime scene",
            "To save us with his...",
            "Suckers!",
            "Nord Stream Pipeline!"
            
        ],
        german: [
            "Was ist mit unserem Gas passiert?",
            "Hat ein Schwertfisch in die falsche Röhre gestochen?",
            "Blasen fliegen nach Walhalla",
            "Nein",
            "Was wäre, wenn wir ein paar Garnelen abrichten würden?",
            "Könnten sie das Loch mit Kelp stopfen?",
            "Opferung des Seeaffen Pöbels",
            "Ja",
            "Die Garnelen wären viel zu dumm",
            "Mit solchen Schätzen umzugehen",
            "Wissen sie das diese Blasen",
            "Sind wie Perlen für uns?",
            "Nein",
            "Wenn wir nur bessere Helfer hätten?",
            "Vielleicht den globalen Tintenfisch?",
            "Wir müssen alle Blasen retten",
            "Ja",
            "Alle unsere Gebete werden erhört",
            "Ein Tintenfischtentakel ist am Tatort",
            "Rettet uns mit seinen...",
            "Saugnäpfen!",
            "Nord Stream Pipeline!",
        ],
        audioUrl: "/album/Nord-Stream-Pipeline.mp3"
    },
    {
        title: "Goldene Groschen",
        englishTitle: "Golden Dimes",
        english: [
            "The moonlight shimmers off the iridescent chrome of the ATM machine like a butterfly emerging from its chrysalis ",
            "The illuminated software interface glows with an otherworldly energy",
            "A hand gloved in beige leather depresses diamond shaped buttons in a curious sequential pattern",
            "A soft hum of mechanistic gears calculate complex transactions",
            "Golden dimes"
        ],
        german: [
            "Das Mondlicht schimmert auf dem schillerndem Chrom des Geldautomaten, wie ein Schmetterling der sich aus seiner Puppe erhebt",
            "Die beleuchtete Softwareoberfläche leuchtet mit einer jenseitigen Energie",
            "Eine mit beigem Leder behandschuhte Hand drückt rautenförmige Knöpfe in einem merkwürdigen sequentiellen Muster",
            "Ein leises Summen mechanistischer Zahnräder berechnet komplexe Transaktionen",

            
        ],
        audioUrl: "/album/Goldene-Groschen.mp3"
    },
    {
        title: "Die Pest",
        englishTitle: "The Plague",
        english: [
            "A flying locust drops a withered corn cob through a basketball hoop.",
            "The locust celebrates it's victory",
            "The plague is inevitable",
            "The corn is delicious",
            "One point for me and one you." ,
            "But the plague has all the points",
            "And the Plague is for me and you"

        ],
        german: [
            "Eine fliegende Heuschrecke lässt einen verwelkten Maiskolben durch einen Basketballkorb fallen.",
            "Die Heuschrecke feiert ihren Sieg",
            "Die Pest ist unvermeidlich",
            "Der Mais ist köstlich",
            "Ein Punkt für mich und einer für dich.",
            "Aber die Pest hat alle Punkte",
            "Das ist für mich und dich"
        ],
        audioUrl: "/album/Die-Pest.mp3"
    },
    {
        title: "Gehirnkühlschrank",
        englishTitle: "Brain Refidgerator",
        english: [
            "Ejaculate",
            "Ovum",
            "Brain...",
            "Refrigerator!",
            
            "Brain refrigerator!",
            
            "Pull the plug",
            "Let it melt",
            "To a puddle of sticky slime",
            "Bring it to the garden",
            "And fertilize the plants",
            
            "Ejaculate",
            "Ovum",
            "Bring it to the garden",
            "Ovum",
            "Ejaculate",
            "Ovum",
            "Brain refrigerator",
            "Ovum"

        ],
        german: [
            "Ejakulat",
            "Ovum",
            "Gehirn...",
            "Kühlschrank!",
            "Gehirnkühlschrank",
            "Stecken sie den Stecker aus",
            "Lass es schmelzen",
            "Zu einer Pfütze klebrigen Schleims",
            "Bring es in den Garten",
            "Und dünge die Pflanzen",
            "Ejakulat",
            "Ovum",
            "Bring es in den Garten",
            "Ovum",
            "Ejakulat",
            "Ovum",
            "Gehirnkühlschrank",
            "Ovum"
            
        ],
        audioUrl: "/album/Gehirnkühlschrank.mp3"
    },
]